// Archivo de configuración de niveles para el juego por medio de mouse
import { inputClasses } from "./input-classes";

export const levels = [
/*  { //NIVEL 1
    gridCols: 12,
    serverCols: [1, 2, 11, 12],
    serverHealth: 40,
    turretsCount: 2,
    turretHealth: 60,
    turretsCols: [ 1, 2],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -20, //Negativo
    zombieHealth: 50,
    zombieDamage: 20,
    zombiesPerLevel: 30,
    maxZombiesOnScreen: 6,
    inputClasses: inputClasses[0],
  },*/
/*  { //NIVEL 2
    gridCols: 12,
    serverCols: [6, 7, 11, 12],
    serverHealth: 40,
    turretsCount: 2,
    turretHealth: 60,
    turretsCols: [ 6, 7],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -20, //Negativo
    zombieHealth: 50,
    zombieDamage: 20,
    zombiesPerLevel: 30,
    maxZombiesOnScreen: 6,
    inputClasses: inputClasses[1],
  },*/
/*  { //NIVEL 3
    gridCols: 12,
    serverCols: [1, 2, 6, 7,],
    serverHealth: 40,
    turretsCount: 2,
    turretHealth: 60,
    turretsCols: [ 6, 7],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -20, //Negativo
    zombieHealth: 50,
    zombieDamage: 20,
    zombiesPerLevel: 30,
    maxZombiesOnScreen: 6,
    inputClasses: inputClasses[2],
  },*/
/*  { //NIVEL 4
    gridCols: 12,
    serverCols: [1, 2, 6, 7, 11, 12],
    serverHealth: 40,
    turretsCount: 2,
    turretHealth: 60,
    turretsCols: [ 6, 7],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -20, //Negativo
    zombieHealth: 50,
    zombieDamage: 20,
    zombiesPerLevel: 40,
    maxZombiesOnScreen: 7,
    inputClasses: inputClasses[3],
  },*/
/*  { //NIVEL 5
    gridCols: 12,
    serverCols: [ 3, 4, 6, 7],
    serverHealth: 40,
    turretsCount: 2,
    turretHealth: 60,
    turretsCols: [ 1, 2],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -20, //Negativo
    zombieHealth: 50,
    zombieDamage: 20,
    zombiesPerLevel: 20,
    maxZombiesOnScreen: 6,
    inputClasses: inputClasses[4],
  },*/
/*  { //NIVEL 6
    gridCols: 12,
    serverCols: [ 7, 8, 11, 12],
    serverHealth: 40,
    turretsCount: 2,
    turretHealth: 60,
    turretsCols: [ 1, 2],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -20, //Negativo
    zombieHealth: 50,
    zombieDamage: 20,
    zombiesPerLevel: 20,
    maxZombiesOnScreen: 6,
    inputClasses: inputClasses[5],
  },*/
/*  { //NIVEL 7
    gridCols: 12,
    serverCols: [ 1, 2, 3, 4, 7, 8],
    serverHealth: 40,
    turretsCount: 2,
    turretHealth: 60,
    turretsCols: [ 1, 2],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -20, //Negativo
    zombieHealth: 50,
    zombieDamage: 20,
    zombiesPerLevel: 40,
    maxZombiesOnScreen: 8,
    inputClasses: inputClasses[6],
  },*/
/*  { //NIVEL 8
    gridCols: 12,
    serverCols: [ 1, 3, 4, 5, 6, 8],
    serverHealth: 60,
    turretsCount: 1,
    turretHealth: 100,
    turretsCols: [ 1],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -20, //Negativo
    zombieHealth: 50,
    zombieDamage: 20,
    zombiesPerLevel: 20,
    maxZombiesOnScreen: 4,
    inputClasses: inputClasses[7],
  }, */
/* { //NIVEL 9 
    gridCols: 12,
    serverCols: [ 1, 2, 6, 7, 11, 12],
    serverHealth: 60,
    turretsCount: 2,
    turretHealth: 100,
    turretsCols: [1, 2],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -70, //Negativo
    zombieHealth: 10,
    zombieDamage: 20,
    zombiesPerLevel: 60,
    maxZombiesOnScreen: 8,
    inputClasses: inputClasses[3],
  }, */
/*  { //NIVEL 10 
    gridCols: 12,
    serverCols: [ 1, 2, 6, 7, 11, 12],
    serverHealth: 60,
    turretsCount: 2,
    turretHealth: 100,
    turretsCols: [1, 2],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -70, //Negativo
    zombieHealth: 10,
    zombieDamage: 20,
    zombiesPerLevel: 60,
    maxZombiesOnScreen: 10,
    inputClasses: inputClasses[3],
  },
  { //NIVEL 11 
    gridCols: 12,
    serverCols: [ 1, 2, 6, 7, 11, 12],
    serverHealth: 60,
    turretsCount: 2,
    turretHealth: 100,
    turretsCols: [1, 2],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -70, //Negativo
    zombieHealth: 10,
    zombieDamage: 20,
    zombiesPerLevel: 80,
    maxZombiesOnScreen: 12,
    inputClasses: inputClasses[3],
  }, */
/*  { //NIVEL 12 
    gridCols: 12,
    serverCols: [ 1, 2, 6, 7, 11, 12],
    serverHealth: 40,
    turretsCount: 2,
    turretHealth: 60,
    turretsCols: [1, 2],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -50, //Negativo
    zombieHealth: 10,
    zombieDamage: 20,
    zombiesPerLevel: 30,
    maxZombiesOnScreen: 8,
    inputClasses: inputClasses[8],
  },*/
/*  { //NIVEL 13 
    gridCols: 12,
    serverCols: [ 1, 2, 6, 7, 11, 12],
    serverHealth: 40,
    turretsCount: 2,
    turretHealth: 60,
    turretsCols: [1, 2],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -70, //Negativo
    zombieHealth: 10,
    zombieDamage: 20,
    zombiesPerLevel: 40,
    maxZombiesOnScreen: 10,
    inputClasses: inputClasses[8],
  },*/
/*  { //NIVEL 14 
    gridCols: 12,
    serverCols: [ 1, 2, 6, 7, 11, 12],
    serverHealth: 40,
    turretsCount: 2,
    turretHealth: 60,
    turretsCols: [1, 2],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -70, //Negativo
    zombieHealth: 10,
    zombieDamage: 20,
    zombiesPerLevel: 80,
    maxZombiesOnScreen: 12,
    inputClasses: inputClasses[8],
  },*/
  { //NIVEL 15 
    gridCols: 12,
    serverCols: [ 1, 2, 3, 4, 5, 6, 10, 11, 12],
    serverHealth: 40,
    turretsCount: 3,
    turretHealth: 60,
    turretsCols: [5, 6, 7],
    bulletVelocityY: 100,
    bulletDamage: 10,
    zombieVelocityY: -20, //Negativo
    zombieHealth: 40,
    zombieDamage: 20,
    zombiesPerLevel: 40,
    maxZombiesOnScreen: 6,
    inputClasses: inputClasses[9],
  },
];
