"""empty message

Revision ID: 2778c823f35a
Revises: e342088559fd
Create Date: 2025-07-28 17:19:03.199511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2778c823f35a'
down_revision = 'e342088559fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_method', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.drop_column('input_method')

    # ### end Alembic commands ###
