"""empty message

Revision ID: a80f9d80cf02
Revises: ab1c665464a9
Create Date: 2025-07-30 16:09:35.516818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a80f9d80cf02'
down_revision = 'ab1c665464a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyboard_game_stats',
    sa.Column('typing_accuracy', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('zombies_killed_by_player', sa.Integer(), nullable=False),
    sa.Column('zombies_killed_by_environment', sa.Integer(), nullable=False),
    sa.Column('total_play_time', sa.Float(), nullable=False),
    sa.Column('bullets_fired', sa.Integer(), nullable=False),
    sa.Column('levels_completed', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouse_game_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('zombies_killed_by_player', sa.Integer(), nullable=False),
    sa.Column('zombies_killed_by_environment', sa.Integer(), nullable=False),
    sa.Column('total_play_time', sa.Float(), nullable=False),
    sa.Column('bullets_fired', sa.Integer(), nullable=False),
    sa.Column('levels_completed', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('zombies_killed_by_player', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('zombies_killed_by_environment', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_play_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bullets_fired', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('typing_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('levels_completed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('input_method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='game_stats_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_stats_pkey')
    )
    op.drop_table('mouse_game_stats')
    op.drop_table('keyboard_game_stats')
    # ### end Alembic commands ###
