"""empty message

Revision ID: ab1c665464a9
Revises: 2778c823f35a
Create Date: 2025-07-30 15:11:03.191366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1c665464a9'
down_revision = '2778c823f35a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    # Elimina el valor por defecto después de actualizar las filas existentes
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.alter_column('created_at', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
