"""empty message

Revision ID: e342088559fd
Revises: 53f80b1a6169
Create Date: 2025-07-28 16:26:45.330099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e342088559fd'
down_revision = '53f80b1a6169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('zombies_killed_by_player', sa.Integer(), nullable=False),
    sa.Column('zombies_killed_by_environment', sa.Integer(), nullable=False),
    sa.Column('total_play_time', sa.Float(), nullable=False),
    sa.Column('bullets_fired', sa.Integer(), nullable=False),
    sa.Column('typing_accuracy', sa.Float(), nullable=False),
    sa.Column('levels_completed', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_stats')
    # ### end Alembic commands ###
