"""empty message

Revision ID: fa8cab7d0457
Revises: 7c81e0dc8b45
Create Date: 2025-07-04 20:24:13.468470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8cab7d0457'
down_revision = '7c81e0dc8b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=32), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
